### ISSUE TITLE
Location versus server config

### ISSUE THREAD

**Issue by brunet-guillaume** [MaloP47/webserv_42#32]
Si (par exemple) maxbodysize est défini dans le bloc server mais pas dans le bloc location, le maxbodysize du server fait foi ?

**Comment by MaloP47** [comment]
Pour le moment, si ce n'est pas specifie dans le bloc location, la taille est fixe a la taille defaut du MBS qui est dans le define. C'est un choix a faire, sinon on peut lui passer la taille du bloc defini dans serveur. Cette question est valable pour d'autres variable. Il faut qu'on decide.

**Comment by brunet-guillaume** [comment]
je suis d'avis de dire que si c'est pas def dans location, on regarde si cest def dans server, et enfin ca prend la valeur par defaut le cas echeant.

**Comment by brunet-guillaume** [comment]
du coup, je pense quil faut modifier ca : 

void	Location::checkMBS( string & block ) {
	char	*endptr ;
	string	tmp = extractStringVariable( block, "client_max_body_size" ) ;
	if ( tmp.empty() ) {
		// Might need to pass Server _maxBodySize if unspecified
		_maxBodySize = MAXCLIENTBS ;
		return ;
	}
	_maxBodySize = strtoll( tmp.c_str(), &endptr, 10 ) ;
	if ( *endptr != 0 || !isAllDigits( tmp ) )
		throw runtime_error( "Wrong client BS format, only digits. In " + _locPath ) ;
}

et qu'elles sont les choses que tu as considere comme obligatoire la dedans (pour location et server, et quelles sont les valeurs par defaut le cas echeant) ? : 

	_root
	_maxBodySize
	_allowedMethod
	_directoryListing
	_errorPage
	_returnURI
	_uploadPath
	_isLocation
	_indexes
